name: code style
# runs the miss hit linter on the code base
# https://github.com/florianschanda/miss_hit/
# see CONTRIBUTING.md for more information

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:  ['*']

jobs:
  style:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip3 install -r requirements.txt

    - name: Install bids-example
    # necessary to avoid errors in miss_hit if the folder is not there
      run: |
         cd tests
         git clone https://github.com/bids-standard/bids-examples.git --depth 1
         cd ..


    - name: MISS_HIT Code style
      run: |
        mh_style --process-slx
