name: miss_hit

on:
  push:
    branches: [master, main, dev]
  pull_request:
    branches: [master, main, dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 1

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      if: github.event.pull_request.base.ref == 'master'
      run: |
        python -m pip install --upgrade pip setuptools
        pip3 install -r requirements.txt

    - name: MISS_HIT Code style
      if: github.event.pull_request.base.ref == 'master'
      run: |
        mh_style --process-slx

    - name: MISS_HIT Metrics
      if: github.event.pull_request.base.ref == 'master'
      run: |
        mh_metric --ci

    - name: MISS_HIT Bug finder
      if: github.event.pull_request.base.ref == 'master'
      run: |
        mh_lint