name: tests_octave

on:
  push:
    branches:
      - master
      - main
      - dev
    paths:
      - '**.m'      
  pull_request:
    branches: ['*']
    paths:
      - '**.m'    

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get -y -qq update
        sudo apt-get -y install octave liboctave-dev

    - name: Clone bids-matlab
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 2

    - name: Install JSONio
      run: |
        git clone https://github.com/gllmflndn/JSONio.git --depth 1
        cd JSONio
        mkoctfile --mex jsonread.c jsmn.c -DJSMN_PARENT_LINKS

    - name: Install bids-example
      run: |
        cd tests
        make data

    - name: MOxUnit Action
      uses: joergbrech/moxunit-action@v1.2.0
      with:
        tests: tests
        src: +bids
        ext: JSONio tests/utils
        with_coverage: false
